services:
  database_service:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env
    volumes: 
      - pg_sorteador-db:/var/lib/postgresql/data

  back-end_service:
    container_name: back-end
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - database_service
    env_file:
      - back-end/.env

  front-end_service:
    build: ./front-end
    container_name: front-end
    volumes:
      - build_react:/var/www/html

  nginx_service:
    build: ./nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - database_service
      - back-end_service
      - front-end_service

volumes:
  pg_sorteador-db:
  build_react: