services:
  postgres_sorteador_db:
    image: postgres
    container_name: postgres_sorteador_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env
    volumes: 
      - pg_sorteador-db:/var/lib/postgresql/data

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_db
    env_file:
      - back-end/.env

  react_sorteador_app:
    build: ./front-end
    container_name: react_sorteador_app
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_sorteador_db
      - node_sorteador_app
      - react_sorteador_app

volumes:
  pg_sorteador-db:
  build_react: